import 'server-only';

import type { SupabaseClient } from '@supabase/supabase-js';

import type { Database } from '@/types/database';

/** Mirrors the payment-slips bucket's own limits (0008_storage.sql). */
const MAX_FILE_BYTES = 5 * 1024 * 1024;
const ALLOWED_TYPES = ['image/jpeg', 'image/png', 'image/webp', 'application/pdf'];

export function isValidSlipFile(file: File): boolean {
  return file.size > 0 && file.size <= MAX_FILE_BYTES && ALLOWED_TYPES.includes(file.type);
}

/**
 * Uploads a payment slip to payment-slips/{roomId}/{invoiceId}/{paymentId}-{filename}
 * (the path convention documented on payments.slip_path) and returns the
 * storage path to store on the payment row, or null if the file was invalid
 * or the upload failed.
 *
 * The payment id is generated by the caller BEFORE the payment row exists,
 * so the slip can be uploaded first and its path included in a single
 * payments insert -- payments_update RLS is admin+, so a staff-recorded
 * payment could never attach a slip via a follow-up update.
 */
export async function uploadPaymentSlip(
  supabase: SupabaseClient<Database>,
  {
    roomId,
    invoiceId,
    paymentId,
    file,
  }: { roomId: string; invoiceId: string; paymentId: string; file: File },
): Promise<string | null> {
  if (!isValidSlipFile(file)) return null;

  const path = `${roomId}/${invoiceId}/${paymentId}-${file.name}`;
  const { error } = await supabase.storage.from('payment-slips').upload(path, file);
  return error ? null : path;
}
